### ISSUE TITLE
block: check box to file a meta:SRG global lock request

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/twinkle#1820]
I propose adding a check box to the block module that, when checked, files a meta:SRG (Steward Requests/Global) request to global lock the account. This comes in handy when doing username blocks of LTAs and really malicious usernames.

* [ ] add check box and description to block module front end
* [ ] use ForeignAPI to see if user is already globally locked. if so, gray out check box or something
* [ ] use ForeignAPI to write the request to meta:SRG
